# Generated by Django 3.0.8 on 2020-07-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('Id_Number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Full_Name', models.CharField(max_length=100)),
                ('Email', models.TextField(max_length=100)),
                ('Contact', models.BigIntegerField()),
                ('Password', models.CharField(max_length=25)),
            ],
        ),
    ]
